#!/bin/sh
# copy .orig files back

find ${1:.} -type f -name '*.orig' -print | /usr/bin/sort | while read FILE
do
    NEW="`dirname $FILE`/`basename $FILE .orig`"
    echo "$NEW" 1>&2
    mv -f $FILE $NEW
done
