#!/bin/sh

cd ~/Software/clisp || exit
tmp=/tmp/cron-clisp.log
log=/var/log/cron-clisp.log

. ~/bin/_cron_common
_cron_pre

(git fetch up && \
    git reset -q --hard up/master && \
    git push -f origin master && \
    git push -f gh master) 2>>$log >>$log

if grep -q '^no changes found' $log; then
    git checkout -q $branch
    if [ x$STASH = x1 ]; then
        git stash -q pop
    fi
    exit
fi

# for the cron mail
cat $tmp
cat $tmp >>$log

git checkout ci && \
  git rebase master && \
  git checkout asan && \
  git rebase ci && \
  git checkout bugfixes && \
  git rebase ci && \
  git checkout translate && \
  git rebase bugfixes && \
  git push origin -f && \
  git push gl -f

_cron_post
