#!/bin/sh

cd ~/Software/ccache
tmp=/tmp/cron-ccache.log
log=/var/log/cron-ccache.log

. ~/bin/_cron_common
_cron_pre

(git pull up && \
    git push -f origin master) 2>>$tmp >>$tmp

if grep -q '^Updating ' $tmp; then
    # need to rebase. pass the log to mail
    true
else
    # early silent exit
    _cron_post
    exit
fi

# for the cron mail
cat $tmp
cat $tmp >>$log
#git submodule update --init >>$log
#git checkout ci && \
#  (git rebase master && git push origin -f) >>$log || git rebase --abort
git checkout msvc-Zi && \
  (git rebase master && git push origin -f) >>$log || git rebase --abort
git push origin -f >>$log

_cron_post
