#!/bin/sh

cd ~/Software/coreutils
tmp=/tmp/cron-coreutils.log
log=/var/log/cron-coreutils.log

. ~/bin/_cron_common
_cron_pre

(git pull up && \
    git push -f origin master) 2>>$tmp >>$tmp

if grep -q '^Updating ' $tmp; then
    # need to rebase. pass the log to mail
    true
else
    # early silent exit
    _cron_post
    exit
fi

# for the cron mail
cat $tmp
cat $tmp >>$log

git submodule update --init >>$log
git checkout advcpmv-1 && \
  (git rebase master && git push origin -f) >>$log || git rebase --abort
git checkout advcpmv && \
  (git rebase master && git push origin -f) >>$log || git rebase --abort
git checkout multibyte && \
  (git rebase master && git push origin -f) >>$log || git rebase --abort
git checkout mb+advcpmv && \
  (git rebase multibyte && git push origin -f) >>$log || git rebase --abort

_cron_post
git push origin -f >>$log
