#!/bin/sh

cd ~/Software/sdcc
branch=`git branch|grep '^\* '|cut -c3-`
STASH=
log=/tmp/cron-sdcc.log

date >$log
git diff | exit
if [ "$branch" != master ]; then
    if git checkout -q master; then
        true
    else
        git stash save cron 2>&1 >>$log
        STASH=1
        git reset --hard    2>&1 >>$log
        git checkout master 2>&1 >>$log
    fi
fi

#(git fetch up && \
#    git reset -q --hard up/master && \
#    git push -f origin master) 2>>$log >>$log
#
#(git checkout ci && git pull --rebase || git rebase --abort) 2>>$log >>$log
#git checkout master  2>>$log >>$log

(git svn fetch && git rebase git-svn && \
    git push -f origin master) 2>>$log >>$log

if grep -q '^no changes found' $log; then
    git checkout -q $branch
    if [ x$STASH = x1 ]; then
        git stash -q pop
    fi
    exit
fi

# for the cron mail
cat $log >>/var/log/cron-sdcc.log
cat $log
#git checkout ci && \
#  git rebase --reapply-cherry-picks master && \
#  git push origin -f

#./upd.sh
git checkout $branch

if [ x$STASH = x1 ]; then
    git stash -q pop
fi
