#!/bin/sh

cd ~/Software/openssh-portable
tmp=/tmp/cron-ssh.log
log=/var/log/cron-ssh.log
. ~/bin/_cron_common
_cron_pre

(git pull up && \
    git push -f origin master) 2>>$tmp >>$tmp

if grep -q '^Updating ' $tmp; then
    # need to rebase. pass the log to mail
    true
else
    # early silent exit
    _cron_post
    exit
fi

git checkout ssh-agent-w 2>>$tmp >>$tmp
if git pull --rebase up master; then
    (git rebase --reapply-cherry-picks master && git push origin -f) 2>>$tmp >>$tmp \
	|| git rebase --abort  2>>$tmp >>$tmp
else
  git rebase --abort  2>>$tmp >>$tmp
fi  

# for the cron mail
cat $tmp
cat $tmp >>$log

_cron_post
git push origin -f >>$log
