#!/bin/sh

cd ~/Software/gperf
tmp=/tmp/cron-gperf.log
log=/var/log/cron-gperf.log

. ~/bin/_cron_common
_cron_pre

(git pull && \
    git push -f origin master) 2>>$log >>$log

if grep -q '^Updating ' $tmp; then
    # need to rebase. pass the log to mail
    true
else
    # early silent exit
    _cron_post
    exit
fi

# for the cron mail
cat $tmp
cat $tmp >>$log
br="long_keys ci hashfuncs nbperf omit-lookup-function no-padding"
for b in $br
do
    git checkout $b
    git pull --rebase origin $b || git rebase --abort
    (git rebase --reapply-cherry-picks master && git push origin -f) || git rebase --abort
done

_cron_post
