#!/bin/sh

cd ~/Software/clisp || exit
branch=`git branch|grep '^\* '|cut -c3-`
STASH=
log=/tmp/cron-clisp.log

date >$log
if [ "$branch" != master ]; then
    if git checkout -q master; then
        true
    else
        git stash save cron 2>&1 >>$log
        STASH=1
        git reset --hard    2>&1 >>$log
        git checkout master 2>&1 >>$log
    fi
fi

(git fetch up && \
    git reset -q --hard up/master && \
    git push -f origin master) 2>>$log >>$log

if grep -q '^no changes found' $log; then
    git checkout -q $branch
    if [ x$STASH = x1 ]; then
        git stash -q pop
    fi
    exit
fi

# for the cron mail
cat $log >>/var/log/cron-clisp.log
cat $log
git checkout ci && \
  git rebase master && \
  git checkout bugfixes && \
  git rebase ci && \
  git checkout translate && \
  git rebase bugfixes && \
  git push origin -f

git checkout $branch
if [ x$STASH = x1 ]; then
    git stash -q pop
fi
