#!/bin/sh
# co master. merge -

br=`git branch | grep ^* | cut -c3-`
git checkout master
# on error reset master to origin/master
git merge --ff $br || (echo "reset master to origin/master"; git merge --abort; git checkout $br)  
