#!/bin/sh
params=""
for f in "$@"; do
  n="$f"
  case "$f" in
  */*)  n=$(echo "$f"|sed -e's,/,::,g')
	;;
  *-*)  n=$(echo "$f"|sed -e's,\([^ ]\)-,\1::,g')
	;;
  esac
  params="$params $n"
done
echo cpan $params
cpan $params
