#!/bin/bash
# needs proper alias p to our new perl
if [ -n "$1" ]; then
    echo "alias p=$1" > ~/.alias-perl
    p=$1
fi
. ~/.alias-perl
cat ~/.alias-perl

exp=~/.cpan/CPAN/nosqlite.pm
jpan="$p -S cpan -j $exp"
cpan="$p -S cpan"

function docmd {
  echo $*
  $*
}

# DBI still broken, Do not use CPAN::SQLite with asan
if [[ $p =~ -asan ]]; then
  echo '# asan special'
  cpan="$jpan"
else
  echo '# bootstrapping CPAN::SQLite'
  # if all the deps would be correct it would be a better world
  docmd $jpan YAML DBI DBD::SQLite File::Which CPAN::SQLite
  # now we should have a working CPAN::SQLite and faster startup
fi

echo '# bootstrapping Bundle::CPANReporter2'
docmd $cpan Params::Util Bundle::CPANReporter2

docmd $cpan B::Flags Opcodes Math::Round Params::Classify
echo $cpan '$(cat ~/Perl/B-C/t/top100)'
$cpan $(cat ~/Perl/B-C/t/top100)

echo "# more? (or Ctrl-C)"
read more
# Class::MethodMaker rm SIGNATURE
docmd $cpan Inline Bundle::CygwinVendor YAML::XS DBIx::Class
# missing Kensho deps
docmd $cpan SQL::Abstract Module::Find Mouse MouseX::Types
# Task::Kensho assumes there is only one archlib per perl, do it manually
perl -lne '/=item L<(.+?)[\|>]/ and print $1' /usr/local/lib/perl5/site_perl/5.14.2/Task/Kensho.pm \
    | xargs $cpan

