#!/bin/sh

test -n $1 || (echo "Usage $0: server"; exit)
tpwd=`pwd`
len=${#HOME}
if [ ${tpwd:0:$len} = $HOME ]; then
    tpwd="~${tpwd:$len}"
fi
files="`git dr|cut -c40-`"
test -z "$files" && exit

for f in $files; do
    echo scp "$f" ${1}:"$tpwd/$f"
done
echo Continue?
read

for f in $files; do
    scp "$f" ${1}:"$tpwd/$f"
done
