#!/bin/sh
# nqp-p6
# relocatable-gh800 \
for b in master threads native_pbc \
         rurban/strip-install_config-gh824 \
         whiteknight/rm_pasm2
do
    fbranch="`echo $b|sed -e's,/,_,'`"
    ~/bin/smoke-parrot $b >/usr/src/parrot/smoked.$fbranch.log 2>&1
done
