#!/bin/bash

test -n $1 || (echo "Usage $0: server [files...]"; exit)
tpwd=`pwd`
len=${#HOME}
if [ ${tpwd:0:$len} = $HOME ]; then
    tpwd="~${tpwd:$len}"
fi
server=$1
shift
files="$@"
test -z $files && exit

echo $files
for f in $files; do
    echo rsync -avzn "$f" ${server}:"$tpwd/$f"
    test -e $f && rsync -avzn "$f" ${server}:"$tpwd/$f"
done
echo Continue?
read

for f in $files; do
    test -e $f && rsync -avz "$f" ${server}:"$tpwd/$f"
done
