#!/bin/bash

test -n "$1" || (echo "Usage $0: server [files...]"; exit)
tpwd=`pwd`
len=${#HOME}
if [ ${tpwd:0:$len} = $HOME ]; then
    tpwd="~${tpwd:$len}"
fi
server=$1
shift
files="$@"
test -z $files && exit

echo $files
for f in $files; do
    echo rsync -avzn ${server}:"$tpwd/$f" "$f"
    rsync -avzn ${server}:"$tpwd/$f" "$f"
done
echo Continue?
read

for f in $files; do
    rsync -avz ${server}:"$tpwd/$f" "$f"
done
